trailingComma: "es5"
useTabs: false
tabWidth: 4
semi: true
singleQuote: false
endOfLine: crlf
printWidth: 80
singleAttributePerLine: true
plugins: [prettier-plugin-tailwindcss]
tailwindConfig: "./tailwind.config.js"
