name: "Codecov"

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    codecov:
        name: Run codecov.io
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
