name: "Formatting"

on:
    push:
        branches: ["main"]
jobs:
    formatting:
        name: Fix formatting issues
        runs-on: windows-latest
        permissions:
            actions: read
            contents: write
            security-events: write
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - name: Install bun
              uses: oven-sh/setup-bun@v1

            - uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
                  cache: "pip" # caching pip dependencies
            - run: pip install -r requirements.txt

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: runs prettier
              run: bun run prettier -w .

            - name: runs black
              run: black main.py

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Prettified Code
