name: "Prettier"

on:
    push:
        branches: ["main"]
    schedule:
        - cron: "50 20 * * *"
jobs:
    fix:
        name: Fix formatting issues
        runs-on: windows-latest
        permissions:
            actions: read
            contents: write
            security-events: write
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - run: echo ".github" > ".prettierignore"

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: runs prettier
              run: npx prettier -w .

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Prettified Code
