name: "Push to Codeberg"

on:
  push:
    branches: ["main"]
jobs:
  push:
    name: Push to Codeberg
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Adds ssh tokens
        run: |
          mkdir -p  ~/.ssh/
          ssh-keyscan codeberg.org > ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSHKEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSHPUBKEY }}" > ~/.ssh/id_ed25519.pub
          ssh-add ~/.ssh/id_ed25519

      - name: Setup Git
        run: |
          git config user.name "Moheshwar Amarnath Biswas"
          git config user.email "${{ secrets.EMAIL }}"
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/
          git remote add codeberg git@codeberg.org:fluentmoheshwar/useful-tools.git

      - name: Pushes to Codeberg
        run: git push codeberg
